name = "svg-converter"
type = "webpack"
account_id = ""  # 填入您的Cloudflare账户ID
workers_dev = true
compatibility_date = "2023-03-01"

[site]
bucket = "./public"  # 静态资源目录
entry-point = "src/index.js"  # 入口文件

[build]
command = "npm run build"
upload.format = "service-worker"

[build.upload]
format = "modules"
main = "./src/index.js"